/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d5407830e66c3960cb213deeeb916139)
interface __BaseEnv_Env {
	BOARD_DB: D1Database;
	BOARD_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BOARD_PASSWORD">> {}
}
